on: [push]

jobs:
  get_credhub_secrets:
    services:
      uaa:
        # Do NOT use this image unless you know what you're doing.
        # It is preconfigured with a credhub client with known
        # username and password for testing purposes.
        image: ghcr.io/ciriarte/insecure-uaa
        ports:
        - 8080:8080

      credhub:
        image: orangeopensource/credhub
        ports:
        - "9000:9000"
        env:
          UAA_URL: http://localhost:8080/uaa
          UAA_INTERNAL_URL: http://uaa:8080/uaa
      
    runs-on: ubuntu-latest
    name: get-credhub-secrets [Unit Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Some Secrets
        run: |-
          TOKEN=$(curl 'http://localhost:8080/oauth/token' -i -X POST \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -H 'Accept: application/json' \
            -d 'client_id=credhub&client_secret=password&scope=scim.write&grant_type=client_credentials&token_format=opaque')

          curl 'https://localhost:9000' -i -X PUT \
              -H 'Content-Type: application/json' \
              -H "Authorization: Bearer $TOKEN" \
              -d '{
            "name": "/some/path/the_ultimate_question_of_life_the_universe_and_everything",
            "type": "value",
            "value": "42"
          }'
      - name: Fetching Secrets
        uses: ./get-credhub-secrets
        id: credhub
        with:
          api: "https://localhost:9000"
          username: "credhub"
          password: "password"
          insecureSkipTLSValidation: "true"
          get: |-
            HITCHHIKER:/some/path/the_ultimate_question_of_life_the_universe_and_everything
            BIRTH_CERTIFICATE: /concourse/main/birth.certificate
          
      - name: Listing the secrets
        run: |-
          echo "The tracker token ${{ steps.credhub.outputs.HITCHHIKER }}"
          echo "A CA cert ${{ steps.credhub.outputs.BIRTH_CERTIFICATE }}"